# Generated by Django 3.2 on 2022-08-17 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20220817_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
