# Generated by Django 3.2 on 2022-08-17 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_alter_student_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='email',
            new_name='student_email',
        ),
    ]
