# Generated by Django 3.2 on 2022-08-17 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_rename_email_student_student_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='student_email',
            new_name='email',
        ),
    ]
