# Generated by Django 3.2 on 2022-08-17 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_rename_student_email_student_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
